// Curated exercise library. Each entry links to a real, existing YouTube
// tutorial (verified titles/IDs) so the "watch how to do this" link on
// the exercise detail page always points at real, correct instructions -
// nothing here is generated or guessed. `goals` ties an exercise to the
// profile goal keys it's relevant for (see profile.tsx's GOALS list) so
// the engine can pick ones that match what the user is actually working
// on; an exercise can serve more than one goal.
const EXERCISES = [
  {
    id: "crunches",
    name: "Crunches",
    goals: ["weight_loss", "insulin_balance"],
    durationLabel: "20 reps × 3 sets",
    level: "beginner",
    description: "A core-strengthening move - stronger abs support posture and help with the metabolic side of PCOD when done regularly.",
    youtubeId: "gEMYUHv8xZg",
  },
  {
    id: "plank",
    name: "Plank",
    goals: ["weight_loss", "insulin_balance", "facial_hair"],
    durationLabel: "30 sec hold × 3 sets",
    level: "beginner",
    description: "A full-body hold that builds core and shoulder strength - regular strength work improves insulin sensitivity, which is often behind PCOD-related facial hair and weight gain.",
    youtubeId: "mwlp75MS6Rg",
  },
  {
    id: "bridge_pose",
    name: "Bridge Pose (Setu Bandhasana)",
    goals: ["regular_cycle", "fertility"],
    durationLabel: "Hold 20-30 sec × 3 rounds",
    level: "beginner",
    description: "A gentle backbend that opens the hips and stimulates the pelvic region - traditionally used to support menstrual regularity and reproductive health.",
    youtubeId: "XMHf6FUGSmk",
  },
  {
    id: "cat_cow",
    name: "Cat-Cow Pose",
    goals: ["regular_cycle", "mood_mental_health", "thyroid"],
    durationLabel: "10 slow rounds",
    level: "beginner",
    description: "A gentle spinal flow synced with breath - eases tension, massages the abdominal organs, and is a calming way to start or end a routine.",
    youtubeId: "6DultLwEJWE",
  },
  {
    id: "butterfly_pose",
    name: "Butterfly Pose (Baddha Konasana)",
    goals: ["regular_cycle", "fertility"],
    durationLabel: "Hold 1-2 min",
    level: "beginner",
    description: "Opens the hips and improves blood flow to the pelvic area - a classic gentle pose for cycle and reproductive health.",
    youtubeId: "SN9oQCE1zMs",
  },
  {
    id: "bodyweight_squats",
    name: "Bodyweight Squats",
    goals: ["weight_loss", "insulin_balance"],
    durationLabel: "15 reps × 3 sets",
    level: "beginner",
    description: "A compound lower-body move that builds muscle, which improves how your body uses insulin - one of the most useful exercises for PCOD.",
    youtubeId: "CKcDiJnLaLY",
  },
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    goals: ["weight_loss", "skin_balance"],
    durationLabel: "30 reps × 3 sets",
    level: "beginner",
    description: "A quick cardio burst that gets your heart rate up and improves circulation - good for weight management and giving skin a healthy glow.",
    youtubeId: "uLVt6u15L98",
  },
  {
    id: "downward_dog",
    name: "Downward-Facing Dog",
    goals: ["mood_mental_health", "hairfall"],
    durationLabel: "Hold 30-45 sec × 3 rounds",
    level: "beginner",
    description: "An inversion that sends fresh blood flow to the scalp and brain - relieves stress and is often recommended to support hair health.",
    youtubeId: "Km2oxamKhhA",
  },
  {
    id: "childs_pose",
    name: "Child's Pose (Balasana)",
    goals: ["sleep_cycle", "mood_mental_health"],
    durationLabel: "Hold 1-2 min",
    level: "beginner",
    description: "A resting pose that calms the nervous system - a gentle way to wind down before bed or reset during a stressful day.",
    youtubeId: "omYNDBYbbu0",
  },
  {
    id: "legs_up_wall",
    name: "Legs-Up-the-Wall Pose",
    goals: ["sleep_cycle", "hairfall", "mood_mental_health"],
    durationLabel: "Hold 5-10 min",
    level: "beginner",
    description: "A restorative inversion that improves circulation and relaxes the body - great before sleep and gentle enough for any energy level.",
    youtubeId: "7AAbw0X30rQ",
  },
  {
    id: "walking_lunges",
    name: "Walking Lunges",
    goals: ["weight_loss", "insulin_balance"],
    durationLabel: "10 reps per leg × 3 sets",
    level: "intermediate",
    description: "Builds leg and glute strength while improving balance - another strength move that helps with insulin sensitivity and weight goals.",
    youtubeId: "BenhAbJiTsw",
  },
  {
    id: "bhramari_breathing",
    name: "Bhramari (Humming Bee) Breathing",
    goals: ["mood_mental_health", "sleep_cycle"],
    durationLabel: "5 min, 8-10 rounds",
    level: "beginner",
    description: "A calming breathing technique that quickly lowers stress and anxiety - stress hormones can worsen PCOD symptoms, so this is worth a few minutes daily.",
    youtubeId: "dFH4Q3J118o",
  },
  {
    id: "thyroid_neck_stretches",
    name: "Neck & Shoulder Stretches for Thyroid",
    goals: ["thyroid"],
    durationLabel: "10 min routine",
    level: "beginner",
    description: "A gentle stretch routine that targets the neck and collarbone area around the thyroid gland - supports thyroid function alongside your treatment plan.",
    youtubeId: "5OXPv4ZOdrA",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    goals: ["weight_loss", "skin_balance"],
    durationLabel: "20 reps × 3 sets",
    level: "intermediate",
    description: "A fast-paced core and cardio move that burns calories and gets circulation going - good for weight management goals.",
    youtubeId: "K3Xt4QH4b-U",
  },
];

module.exports = { EXERCISES };
